### ISSUE TITLE
Requesting permission to make a pull request

### ISSUE THREAD

**Issue by mbcoder** [akullpp/awesome-java#1069]
I was trying to make a pull request to add a new entry in your geospatial section which would look something like this:

```
[ArcGIS Maps SDK for Java](https://github.com/Esri/arcgis-maps-sdk-java-samples/) - JavaFX library for adding mapping and GIS functionality to desktop apps
```

I created a branch from master and when I tried to push this with a view to making a pull request it responded with:

```
ERROR: Permission to akullpp/awesome-java.git denied to mbcoder.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```

If my entry is acceptable, can you add me to the authorised contributors so I can make a pull request?

**Comment by jonatan-ivanov** [comment]
You need to fork the project, push your changes on a branch of your fork and you can open a PR from your fork to this project (see the other PRs). Please read the GitHub docs for more information.

**Comment by mbcoder** [comment]
Thanks @jonatan-ivanov that makes sense, I'll follow that approach
