### ISSUE TITLE
Dynamic Jasper link redirects to some kind of betting website

### ISSUE THREAD

**Issue by zford-reitz** [akullpp/awesome-java#1100]
The link for Dynamic Jasper (http://dynamicjasper [dot] com/) redirects to some kind of betting website (https://www.rockhillchina [dot] com/).

It looks like Dynamic Jasper has moved their website to:
https://intive-fdv.github.io/DynamicJasper/

so I guess that should be the new link target.

I've also created an Issue on their repo, since they have links to the redirecting website in their README. See: https://github.com/intive-FDV/DynamicJasper/issues/145

**Comment by akullpp** [comment]
Thanks, I changed the URL.
