### ISSUE TITLE
Proposal: Reactive section

### ISSUE THREAD

**Issue by krisskross** [akullpp/awesome-java#178]
Hi

Since the term "reactive" is getting so much momentum in the industry today I think it make sense to have a separate section for libraries that address this specifically.

Propose to move RxJava, Reactor, akka, etc to this section. I would also add the standardization effort reactive-streams targeted for Java 9 https://github.com/reactive-streams/reactive-streams-jvm.

Cheers,
-Kristoffer

**Comment by akullpp** [comment]
Good idea, will merge the PR.
