### ISSUE TITLE
two urls are not working

### ISSUE THREAD

**Issue by Hauwertlhaufn** [akullpp/awesome-java#193]
These two urls are not working:

Javassist - Tries to simplify the editing of bytecode. 
-> http://www.csg.ci.i.u-tokyo.ac.jp/~chiba/javassist/

Unitils - Testing library divided into modules for unit and integration testing.
-> http://www.unitils.org/

**Comment by krisskross** [comment]
Fixed Javassist. Unitils url seems legit but down?

**Comment by Hauwertlhaufn** [comment]
On http://sourceforge.net/projects/unitils/?source=directory you can still find the project, so may you want to switch to this url?

**Comment by krisskross** [comment]
It says "temporarily offline", I would expect the site to come back up?

**Comment by Hauwertlhaufn** [comment]
Yes, I think that that was my fault. Sorry for that one.
