### ISSUE TITLE
Extend 'Security' section to cover security tools as well as libraries

### ISSUE THREAD

**Issue by psiinon** [akullpp/awesome-java#205]
Or create another section, if thats more appropriate.
I'd like to suggest OWASP ZAP for this section: https://www.owasp.org/index.php/OWASP_Zed_Attack_Proxy_Project
Disclaimer, I am the project lead :/
Happy to send a PR, but as the Security section is currently scoped to just libraries I thought I'd raise that as an issue first :)

**Comment by akullpp** [comment]
I'm not sure how this is related to Java as language, could you explain?
