### ISSUE TITLE
FlexyPool

### ISSUE THREAD

**Issue by vladmihalcea** [akullpp/awesome-java#261]
Although it's a framework I wrote myself, I think it's worth taking a look on it since it might fit in the "(d) a niche product that fills a gap" section.

[FlexyPool](https://github.com/vladmihalcea/flexy-pool) brings all sorts of connection-related metrics to the most common connection pooling solutions. It also allows you to define fail-over strategies, to reduce the likelihood of getting a connection acquisition failure.

**Comment by akullpp** [comment]
Looks great, please open a PR.
