### ISSUE TITLE
Code Coverage Tools?

### ISSUE THREAD

**Issue by VijayKrishna** [akullpp/awesome-java#266]
Any reason why code coverage tools and libraries have been left out of this list?
- Jacoco - http://eclemma.org/jacoco/
- Cobertura - http://cobertura.github.io/cobertura/
- JCov - https://wiki.openjdk.java.net/display/CodeTools/jcov
- Clover - https://www.atlassian.com/software/clover/overview
- EMMA - http://emma.sourceforge.net/
- Serenity - https://wiki.jenkins-ci.org/display/JENKINS/Serenity+Plugin

**Comment by akullpp** [comment]
The reason: nobody send a pull request. You could be the first... :)
