### ISSUE TITLE
JVM Languages

### ISSUE THREAD

**Issue by pron** [akullpp/awesome-java#267]
1. The languages list is not alphabetized
2. There are (many) dozens of JVM languages. It's hard to decide which should be listed. In any event, if the obscure Golo is listed, probably many more should, and in that case perhaps the section be removed completely (moved to a different repo?)

**Comment by krisskross** [comment]
I agree that other JVM languages doesn't belong. People browsing awesome-java are probably looking for Java related stuff.

I suggest to put it here, https://github.com/deephacks/awesome-jvm

**Comment by akullpp** [comment]
Agreed, this would be a quite long list with doubtful usefulness.

**Comment by pron** [comment]
I don't understand. You've agreed that the category should be gone and closed the issue, yet the category is still there (and still not alphabetized)...

**Comment by akullpp** [comment]
I deleted it an hour later, see referenced PR.
