### ISSUE TITLE
Vert.x is in the wrong category

### ISSUE THREAD

**Issue by pron** [akullpp/awesome-java#268]
It belongs in Web Frameworks, not Development.

**Comment by tircis** [comment]
Why do you think it's a Web Framework ? You can build much more than a web site with Vert.x
From vertx.io: "Vert.x is a tool-kit for building reactive applications on the JVM"

**Comment by tircis** [comment]
Why do you think it's a Web Framework ? you can build much more than a web site with Vert.x.
From vertx.io: "Vert.x is a tool-kit for building reactive applications on the JVM"

**Comment by pron** [comment]
In that case it should go under Reactive Libraries. In any case, it doesn't belong in the Development category, as it has much more to do with the other products in the Web Framework category or the Reactive Libraries category than the ones in its current category.

**Comment by tircis** [comment]
Reactive Libraries is a better category, I agree

**Comment by akullpp** [comment]
Reactive Libraries seems best. Please send a PR and it will be merged.
