### ISSUE TITLE
Vibur DBCP

### ISSUE THREAD

**Issue by simeonmalchev** [akullpp/awesome-java#293]
Vibur DBCP is a mature JDBC connection pool library on which I've been working myself over the last 2 years, and I think it's worth considering for inclusion in the Database section as it may fit under requirement "(c) unique in its approach and function" and/or "(d) a niche product that fills a gap".

Suggested entry to add at the end of the ##Database section:

* [Vibur DBCP](http://www.vibur.org/) - JDBC connection pool library which offers advanced performance monitoring capabilities.

**Comment by tedyoung** [comment]
:+1: Why not go ahead and create a Pull Request to add that? Let us know if you need help doing that.

**Comment by akullpp** [comment]
Done.
