### ISSUE TITLE
JSON vs JSON Processing categories

### ISSUE THREAD

**Issue by akullpp** [akullpp/awesome-java#295]
#276 suggests splitting the JSON category in **JSON** for *Libraries for serializing and deserializing JSON to and from Java objects.* and **JSON Processing** for *Libraries for processing data in JSON format.*

I feel that this might not lead to any benefits and would like a wider range of opinions.

**Comment by tedyoung** [comment]
:+1: I think it's a useful separation. If not separated, each entry would have to have information about whether they're more "general-purpose" JSON libraries (used for HTTP APIs), or are more about manipulation/searching.

**Comment by akullpp** [comment]
Okay, a separate section will be added.
