### ISSUE TITLE
Can you add any license to your project or said me what license does used in your project? 

### ISSUE THREAD

**Issue by Vedenin** [akullpp/awesome-java#336]
Hello All

Sorry for this question, but I tried to find any license in your project, but I couldn't. It's possible to add any license to this project or said me what license is used in your project? I want to do some fork of your project, but I don't know it's possible or not.

Thank you in advance, 
Slava

**Comment by ItzSkillz** [comment]
since there isn't any license listed on this repo, the author reserves all rights. however this might be a good time to add a license.

**Comment by akullpp** [comment]
Good point, I would choose CC-BY-SA-4.0 since major improvements to this list - which was created as open-source project - should be publicly available too.
