### ISSUE TITLE
Proposal: jabba - Java Version Manager inspired by nvm

### ISSUE THREAD

**Issue by shyiko** [akullpp/awesome-java#337]
Hi. 

Would you consider adding [jabba](https://github.com/shyiko/jabba) (Java Version Manager inspired by nvm/gvm/rvm) to this list? It's fairly new so I understand why it might not get be accepted but it's quite unique in Java world in that it's the only (to my knowledge) tool that allows automated Oracle JDK/Zulu OpenJDK installation & seamless switching between different releases.

Thank you.

(disclosure: I'm the author of the project)

**Comment by akullpp** [comment]
Sounds exactly like the thing we seek, please do a PR. :)
