### ISSUE TITLE
Spring framework category

### ISSUE THREAD

**Issue by benas** [akullpp/awesome-java#346]
Hi,

Thank you for this really awesome list!

Just a note about Spring framework (the core). Currently, it is placed under "Web Frameworks" category, I do believe it fits better under "Dependency Injection".

It is more precise to put "Spring MVC" under "Web frameworks" and move the Spring framework (link to core) to "Dependency Injection".

What do you think? I can send a pull request if you agree.

Kind regards
Mahmoud

**Comment by akullpp** [comment]
That's a good idea, could you please make a pull request?
