### ISSUE TITLE
Apache Tapestry git repository URL is not correct

### ISSUE THREAD

**Issue by bouil** [akullpp/awesome-java#348]
The web page https://java.libhunt.com/project/tapestry-cometd is labelled "Apache Tapestry", but the URL of the page and the Github repository refer to a unofficial tool named "Tapestry cometd", not related to Apache Tapestry web framework.

The correct repository is https://github.com/apache/tapestry-5 (mirror git://git.apache.org/tapestry-5.git).

**Comment by akullpp** [comment]
Changed, thanks for mentioning this.

**Comment by akullpp** [comment]
I don't know what you mean, the link for Apache Tapestry in the README.md is http://tapestry.apache.org/

If you think there's something wrong with that, please submit a PR.

**Comment by bouil** [comment]
Hi, I'm meaning the **GIT ** repository URL, not the project home page.

**Comment by akullpp** [comment]
Where do we use the Git URL?

**Comment by bouil** [comment]
https://java.libhunt.com/project/tapestry-cometd ?

**Comment by bouil** [comment]
I would be glad to create a PR, but I can't see how this website (https://java.libhunt.com/ ) is generated from this git repository.

**Comment by akullpp** [comment]
This GitHub repository is not related to the aforementioned website. You should contact the administrator of said website since there's nothing we can do to influence this unrelated website.

**Comment by bouil** [comment]
Ok, my bad, or maybe this website bad, because they are pointing to you for any contribution !
See https://java.libhunt.com/contribute

Sorry for the noise.
