### ISSUE TITLE
java.libhunt.com

### ISSUE THREAD

**Issue by StanBright** [akullpp/awesome-java#350]
Hi,

I released java.libhunt.com this week. It is based on the list here, and https://github.com/akullpp/awesome-java is referenced as the official repo. Do you think it makes sense to set java.libhunt.com as the website for this repo?

**Comment by akullpp** [comment]
No, there will never be an official website. It is a simple list in a GitHub repository, nothing more. Everyone is free to write their own frontend layer.

**Comment by StanBright** [comment]
Fair enough.

**Comment by akullpp** [comment]
I added it as **a** frontend to this list.

**Comment by StanBright** [comment]
Thumbs up!

**Comment by FashionVon** [comment]
fantastic！

**Comment by last-khajiit** [comment]
Nice, thumbs up!
