### ISSUE TITLE
no markdown libraries

### ISSUE THREAD

**Issue by DouweKoopmans** [akullpp/awesome-java#358]
there should be a category for markdown rendering libraries.

to list a few examples:
[pegdown](https://github.com/sirthias/pegdown)
[commonmark-java](https://github.com/atlassian/commonmark-java)
[txtmark](http://github.com/rjeschke/txtmark)
[markdown4j](http://code.google.com/p/markdown4j)
[markdownpapers](http://markdown.tautua.org/)

**Comment by jbduncan** [comment]
If a Markdown category were to be considered, I think it should really be a general category for Text-to-text Converters, which would include not only Markdown libs but also [Asciidoc](https://en.m.wikipedia.org/wiki/AsciiDoc) lib(s) like [AsciidoctorJ](http://asciidoctor.org/docs/asciidoctorj/).

**Comment by akullpp** [comment]
Please create a pull request with the most awesome and active markdown libraries. However, you should consider to add a more general category like @jbduncan said.
