### ISSUE TITLE
Consider https://github.com/google/FreeBuilder

### ISSUE THREAD

**Issue by dminkovsky** [akullpp/awesome-java#371]
It's awesome <3

**Comment by akullpp** [comment]
Please make a PR and if you want you could also add https://github.com/google/auto

Maybe even create a new category `Code Generators` and add Lombok to it.

**Comment by jbduncan** [comment]
`Immutables` from the **Development** section should be moved to **Code Generators** as well, as it fulfills the same purpose of `AutoValue` and `FreeBuilder`.

**Comment by dminkovsky** [comment]
@jbduncan Thanks. I updated.
