### ISSUE TITLE
Apache Cayenne

### ISSUE THREAD

**Issue by dkoyro** [akullpp/awesome-java#450]
What do you think about Apache Cayenne? 
http://cayenne.apache.org/ 
This is a powerful, full-featured, open-source object relational mapping framework created for developers working with relational databases.

**Comment by aadrian** [comment]
Because it has a very useful Modeler out of the box, it's very easy to learn and use.

IMHO it's not getting the publicity it deserves :).

**Comment by akullpp** [comment]
See #450 is it better suited for code generation section?
