### ISSUE TITLE
[Suggestion]Voldmort can be add to distributed-databases group 

### ISSUE THREAD

**Issue by stoneCrystal** [akullpp/awesome-java#471]
I suggest Voldmort can be add to distributed-databases group

**Comment by jbduncan** [comment]
Hi @stoneCrystal, can you give us a link to this Voldmort project, or even raise a Pull Request perhaps? :)

**Comment by jbduncan** [comment]
Looks like a good project to add to the list to me.

I'm sure that if you raise a PR for this, @akullpp would be happy to review it. :)

Do you know how to raise PRs (Pull Requests) on GitHub? Is it something you'd have the time and willingness to do?

**Comment by akullpp** [comment]
Please create a PR with a meaningful description.
