### ISSUE TITLE
Polyglot Maven

### ISSUE THREAD

**Issue by heldev** [akullpp/awesome-java#482]
Hi,
Unfortunately, there is no awesome-maven list, but it seems [Polyglot Maven](https://github.com/takari/polyglot-maven) project still worth mentioning. Yes, it's not a separate build tool, but it's quite unique and it can noticeably change Maven usage. It even has [IDEA support OOTB](https://blog.jetbrains.com/idea/2016/09/intellij-idea-2016-3-eap-polyglot-maven-grails-view-inspections-and-more/).
Do you think we can fit, this project in the list, by any chance?

**Comment by akullpp** [comment]
Sounds good, please do a pull request. You could also start an awesome-maven list. ;-)
