### ISSUE TITLE
Linear algebra libraries

### ISSUE THREAD

**Issue by acisternino** [akullpp/awesome-java#485]
Hi,

For $WORK I came across this website: https://java-matrix.org

It is an excellent list of all the matrix manipulation and linear algebra libraries for Java.

Given that none of them is alreay listed here, I think that at least some of them would be a very useful addition to the list.

I see two options: we either list the site in one of the general sections or we create a new dedicated "Linear Algebra" section with the libraries (minus those clearly obsolete).

[Java Matrix Benchmark](http://lessthanoptimal.github.io/Java-Matrix-Benchmark/) is also a closely related and very useful resource.

Comments?

**Comment by akullpp** [comment]
You should do this, but keep in mind the contribution rules. The library shouldn't be abandoned or have a very specific function which no other library fulfils. Often neither is the case for academic projects.
