### ISSUE TITLE
Should we include plugins for IDEs or other applications?

### ISSUE THREAD

**Issue by akullpp** [akullpp/awesome-java#489]
Example: #484

**Comment by heldev** [comment]
Let me put my two cents in:

- Some plugins are very Java-specific (e.g. Lombok or that Folder) and only Java users can appreciate them because they don't make sense outside of the Java ecosystem

- If the group gets big enough we can always extract it to a separate awesome-list

**Comment by akullpp** [comment]
Okay, I allow it.
