### ISSUE TITLE
Book descriptions

### ISSUE THREAD

**Issue by heldev** [akullpp/awesome-java#491]
I'm wondering what you think about book descriptions? It's good to know why a book is on the list right?
For example, I would like to add [Java SE8 for the Really Impatient: A Short Course on the Basics](https://www.amazon.com/Java-SE8-Really-Impatient-Course/dp/0321927761/ref=sr_1_2/163-7805743-9317311?ie=UTF8&qid=1489861817&sr=8-2&keywords=java+8+for+impatient) I recommend this book quite often because it's concise (< 200 small pages), it contains information only about Java 7 (20 pages) and Java 8 (180 pages, or 130 without Nashorn and JavaFX). As a result, the book is great to people who know Java <= 7 but not to newbies. It seems to be worth of mentioning.

**Comment by akullpp** [comment]
The category is called Influential Books: Books that had a high impact and are still worth reading. I don't know if this book you suggest fits in that category and I'm sure we don't want to list every book  about Java.
