### ISSUE TITLE
Java Version Managers

### ISSUE THREAD

**Issue by steve-didomenico** [akullpp/awesome-java#503]
Hi all,

I'll be adding a pull request for Java Version Managers. I see jabba is already on the list; I found two more (jenv and SDKMan), both of which appear to be popular with many more github stars than jabba. Both projects appear to be maintained on a regular basis. There are many scripts which do similar things, but these appear to offer the most functionality and are the most well-known. (Though I'm sure I may have missed some others).

Since there are three of these utilities, I created their own section as well.

**Comment by akullpp** [comment]
Added
