### ISSUE TITLE
New contribution rules and re-evaluation

### ISSUE THREAD

**Issue by akullpp** [akullpp/awesome-java#511]
## Contribution Rules

One of the main problems of awesome-* lists in general is the aspect of curation and quality regarding the descriptions. I don't want this list to be just a mere "merge every PR that matches" list like so many others.

So I added two strict criteria to the set of contribution rules:

> If an entry has a similar scope as other entries in the same category, the description must state the unique features that distinguishes it from the other entries.

> If an entry does not met conditions there has to be an explanation either in the description or the pull request why it should be added to the list.

I think it's acceptable to ask for a bit more time investment from the authors of the pull requests since I also invest a lot of time.

The rules will be enforced strictly in the next months to see if the quality improves.

## Re-evaluation

At the beginning this list had a very tight re-evaluation cycle (weekly/monthly) of the entries since it was smaller. I plan to re-evaluate every single item in the next weeks to have a quality improvement. I now plan to do this every 6 months.

Libraries that are discontinued or don't match the criteria anymore will be deleted with a single PR so that people can criticize the decision.

**Comment by jbduncan** [comment]
That sounds like an ambitious (in a very good way) plan to me, so I approve!

**Comment by akullpp** [comment]
Related commit: d4406a3e1e
