### ISSUE TITLE
Add (distributed) transactions section?

### ISSUE THREAD

**Issue by nmcl** [akullpp/awesome-java#525]
Was wondering if there'd be value in adding a section on transactions projects such as Bitronix and Narayana? Although local transactions are often a part of relational databases, these transactions projects can be used with a variety of data sources and at least one of them also supports forward compensation models, software transactional memory and RESTful transactions. If the idea is accepted I'll raise a pull request.

**Comment by akullpp** [comment]
See 1023d1d85d593513030583c6cb0ed76182c12a8c
