### ISSUE TITLE
Clarify contribution guidelines

### ISSUE THREAD

**Issue by jbduncan** [akullpp/awesome-java#567]
Specifically, clarify that:
1. ~~New entries will likely not be added if they've not been around "long enough" to prove their awesomeness, e.g. 3 months or so.~~
2. Entries that don't fit any of the pre-existing specialised sections should go under **Miscellaneous**.
3. If two or more entries in **Miscellaneous** are about the same thing, then they can be moved to a new specialised section.

**Comment by jbduncan** [comment]
Related to #563, where these points were raised.

**Comment by akullpp** [comment]
I agree with (2) and (3) but find (1) difficult. The question is whether we want hard criteria like 3 months or 50 stars since this would eliminate the possibility to kick-start awesome yet unknown libraries, wouldn't it?

**Comment by jbduncan** [comment]
Good point... Not easy to come up with a useful objective metric, eh? ;)

I don't have any better ideas ATM, so I'm happy to change this issue so that (1) is crossed-out and only (2) and (3) are dealt with in the meantime, if you're happy?

**Comment by akullpp** [comment]
Changed the contribution file according to the result of this discussion, see #315e809
