### ISSUE TITLE
Update summary

### ISSUE THREAD

**Issue by akullpp** [akullpp/awesome-java#570]
Related discussion #546 

How can we precisely capture the intent of the list?

Currently: `A curated list of awesome Java frameworks, libraries and software.`

Suggestions:
`A curated list of awesome frameworks, libraries and software for Java.`
`A curated list of awesome frameworks, libraries and software for the Java programming language.`

`for Java developers` would be to general I think, since this would comprise tools like Docker, etc.

**Comment by jbduncan** [comment]
I think "A curated list of awesome frameworks, libraries and software for the Java programming language." sounds best. It kind of implies to me that tools which aren't necessarily implemented in Java but have use in the Java programming language ecosystem in a non-overly general way are accepted, e.g. Facebook's Infer.

**Comment by akullpp** [comment]
Done.
