### ISSUE TITLE
Add parser combinator library?

### ISSUE THREAD

**Issue by kanishka-azimi** [akullpp/awesome-java#588]
[jparsec](https://github.com/jparsec/jparsec) meets some of the criteria, but not all. It would be a nice addition to "compiler-compiler" for lack of an existing parser section. jparsec is a nice compromise between the simplicity of implementing a recursive descent parser directly and the robustness and performance of using a parser generator for parsing problems.

> (a) widely recommended, regardless of personal opinion

Not widely recommended (probably for lack of awareness). Similar libraries are widely used in other languages.

> (b) highly discussed in the community due to its innovative nature

It doesn't appear to have many discussion hits in a Google search.

> (c) absolutely unique in its approach and function

It is unique.

> (d) a niche product that fills a gap

Fills a gap in allowing for more robust, readable parsing than using Scanner only, but simpler to use than starting with a full parser generator. Library's [tutorial](https://github.com/jparsec/jparsec/wiki/Tutorial) for getting familiar with general usage.

------

It has some [benchmarks](https://github.com/jparsec/jparsec/blob/1349a88b0e9333615adcdb2baa242f026f12cf6c/parsing-made-easy/slides/README.md#performance-graphs) that indicate it performs reasonably well. The code has had steady progress and been around for a while (https://github.com/jparsec/jparsec/graphs/contributors). There don't seem to be any critical bugs or PRs outstanding.

I haven't used the library yet, but I can report back in this discussion thread as I get a chance to use it (1-2 months from now).

CC: @abailly

**Comment by abailly** [comment]
In my humble but biased opinion, there is no comparison in ease of use between a parser combinators library and a full-blown parser generator like antlr. jparsec is not widely used mostly because 1/ it is not widely known and 2/ people very rarely build parsers those days and those who do usually follow approach of adapting existing grammars.

I became maintainer of jparsec because I have used it successfully on various projects that required parsing capabilities. And Ben, the original creator of the library, ported it to Java 8 syntax which makes it even more a breeze to use.

**Comment by kanishka-azimi** [comment]
I thought I was going into Java, but it looks like C++ instead currently. I will close for now, and reopen if I end up in Java.

**Comment by jbduncan** [comment]
@kanishka-azimi This repository is, indeed, awesome-java, not awesome-c++, so if you were thinking that you opened an issue in the wrong repository, be assured that it isn't.

I don't know about @akullpp, but I've personally not been paying much attention to awesome-java of as late as my time has been limited and I've spent my spare time on other open source projects, so apologies for not responding sooner.

I think this project looks cool and is worth integrating into awesome-java. We're open to a PR if you're willing to open one. :)

**Comment by jbduncan** [comment]
Cosing this issue again, and just to reiterate: we're open to PRs. :)
