### ISSUE TITLE
Hudson is no longer under development

### ISSUE THREAD

**Issue by esuomi** [akullpp/awesome-java#599]
As the README states under _Ancients_,

> Hudson - Continuous integration server still in active development.

This, however, is no longer the case. To quote [Eclipse Foundation's wiki on Jenkins](https://wiki.eclipse.org/Jenkins):

> Since Hudson is not maintained anymore, Jenkins is the replacement for it.

There's also references and history available in eg. https://en.wikipedia.org/wiki/Hudson_(software) for the interested but as can be seen from this, it has no place in this list anymore.

**Comment by akullpp** [comment]
I agree, deleted.
