### ISSUE TITLE
Add concurrency section

### ISSUE THREAD

**Issue by harryganz** [akullpp/awesome-java#626]
I found this repo while looking for a good implementation of CSP (Communicating Sequential Processes) in Java. Can you add a section for concurrency/parallelism libraries. BTW, I found https://github.com/jetlang/core which seems to be a nice high-level implementation of CSP.

**Comment by akullpp** [comment]
Please create a pull request and mind the Contribution guidelines. If you just have one library to be added, you can't create a new category. There have to be at least 2-3 entries.
