### ISSUE TITLE
Add inspectIT

### ISSUE THREAD

**Issue by mariusoe** [akullpp/awesome-java#639]
Hi,

I opened a PR (#638) which has been rejected because I think I added too less information why this tool should be added and what's unique about it.

inspectIT is an open source APM tool to monitor and analyze (which can be very helpful for development) an application. You are able to hook into a Java application and are able to capture detailed run-time information (like method calls, executed SQL statements, CPU timings, etc). And these hooks can be changed on the fly while the application is running. Furthermore, it supports tracing over multiple system. So if you e.g. have a micro-service architecture, you see how a request is propagated over multiple systems (additionally, it supports the OpenTracing API).
Another point is that it can be used to execute end user monitoring, for example, how long took the page loading for the users, how many resources are loaded, ..., and correlate all these data together, which is unique for such open source tool.

Greets,
Marius

**Comment by akullpp** [comment]
That's a great description. I will add it.
