### ISSUE TITLE
Add OctoLinker browser extension

### ISSUE THREAD

**Issue by stefanbuck** [akullpp/awesome-java#642]
I've opened this issue, because I don't know where to put my suggestion. [OctoLinker](https://github.com/OctoLinker/browser-extension)  is a browser extension for GitHub wich turns import statements into clickable links. 

For example 

```java
import org.springframework.integration.x.twitter.TwitterSearchChannelAdapter.ResultType
``` 

will point to https://docs.spring.io/spring-xd/docs/1.3.2.RELEASE/api/org/springframework/integration/x/twitter/TwitterSearchChannelAdapter.ResultType.html

It also links java SE and EE imports to their documentation page.

![](https://user-images.githubusercontent.com/1393946/33520483-f1856e3e-d7bb-11e7-9065-8e99c2b391ea.gif)

Currently just a few projects are supported:

- java SE and EE core packages
- Junit
- mockito
- jslf4j
- hamcrest
- jackson-core
- jackson-annotations
- jackson-databind
- Spring AMQP
- Spring for Android
- Spring Batch
- Spring Boot
- Spring Cloud CLI
- Spring Cloud Cluster
- Spring Cloud Commons
- Spring Cloud Config
- Spring Cloud Connectors
- Spring Cloud Consul
- Spring Cloud Contract
- Spring Cloud Data Flow
- Spring Cloud Data Flow for Cloud Foundry
- Spring Cloud Data Flow for Kubernetes
- Spring Cloud Data Flow for Apache Mesos
- Spring Cloud Data Flow for Apache YARN
- Spring Cloud Function
- Spring Cloud GCP
- Spring Cloud Netflix
- Spring Cloud Pipelines
- Spring Cloud Skipper
- Spring Cloud Sleuth
- Spring Cloud Spinnaker
- Spring Cloud Stream
- Spring Cloud Stream App Starters
- Spring Cloud Task
- Spring Cloud Task App Starters
- Spring Cloud Vault
- Spring Cloud Vault
- Spring Cloud Zookeeper
- Spring CredHub
- Spring Data Commons
- Spring Data Envers
- Spring Data GemFire
- Spring Data JDBC Extensions
- Spring Data JPA
- Spring Data LDAP
- Spring Data MongoDB
- Spring Data Neo4J
- Spring Data Redis
- Spring Data REST
- Spring Data for Apache Solr
- Spring Framework
- Spring for Apache Hadoop
- Spring HATEOAS
- Spring Integration
- Spring LDAP
- Spring Mobile
- Spring REST Docs
- Spring Security
- Spring Security Kerberos
- Spring Security OAuth
- Spring Session
- Spring Session MongoDB
- Spring Shell
- Spring Social
- Spring Social Facebook
- Spring Social Twitter
- Spring Statemachine
- Spring Vault
- Spring Web Flow
- Spring Web Services
- Spring Cloud Bus
- Spring Cloud for Cloud Foundry
- Spring Cloud Cloud Foundry Service Broker
- Spring Cloud Data
- Spring Cloud Security
- Spring Data for Apache Cassandra
- Spring Data Couchbase
- Spring Data Elasticsearch
- Spring for Apache Kafka
- Spring Security SAML
- Spring Social GitHub
- Spring Social LinkedIn
- Spring Social TripIt
- Spring Data Graph
- Spring Flex
- Spring XD

It also has support for JavaScript, Ruby, Go, Pyhton, Rust, Haskell.

Please let me know if you would accept a PR for it.

**Comment by akullpp** [comment]
Thanks, added in d48fb259b472080ccb3

**Comment by stefanbuck** [comment]
Amazing, thank you
