### ISSUE TITLE
Consider adding “Spark with Java”

### ISSUE THREAD

**Issue by jgperrin** [akullpp/awesome-java#672]
Hello,

Please consider adding “Spark with Java” to your awesome list.

* [Spark with Java](https://www.manning.com/books/spark-with-java) - Apache Spark is written in Scala, therefore there is this urban legend that you need to learn Scala to use Spark. This new book on Spark, in Manning's Early Access Program (MEAP), offers a very strong focus on Java, targeted towards software and data engineers. The author focuses on leveraging existing skills rather than learning Scala and Hadoop at the same time. You can find the accompanying examples, all in Java, in the linked [GitHub repositories](https://github.com/topics/sparkwithjava).

Thanks!

**Comment by akullpp** [comment]
Unfortunately the book has a focus on a specific library and not the language itself. This list lists only "timeless" books about the Java programming language, not libraries. Feel free to open a discussion if you think this should be changed.
