### ISSUE TITLE
Section "development" doesn't make much sense

### ISSUE THREAD

**Issue by helmbold** [akullpp/awesome-java#676]
The section "development" doesn't make much sense since the whole collection is about "development".  If you look at the items in this sections you can hardly see any coherence. How is RxJava, Auto and ADT4J releated?

>ADT4J - Algebraic Data Types for Java (JSR-269 code generator).
AspectJ - Seamless aspect-oriented programming extension.
Auto - Collection of source code generators.
DCEVM - Modification of the JVM that allows unlimited redefinition of loaded classes at runtime.
Immutables - Scala-like case classes in standard Java.
JRebel - Commercial software that instantly reloads code and configuration changes without redeploys.
Lombok - Code-generator which aims to reduce the verbosity of Java.
RxJava - Library for composing asynchronous and event-based programs using observable sequences from the JVM.
Spring Loaded - Another class reloading agent for the JVM.
vert.x - Polyglot event-driven application framework for the JVM.

I suggest to move the items to other sections (for example RxJava could be moved to the section where the similar Reactor resides) or to create new sections with meaningful names.

**Comment by akullpp** [comment]
Where do you see RxJava listed in the *Development* section? It is listed in *Reactive libraries* as it should be. It seems that you are referring to an entirely different list.

The development section contains tools that "augement the development process at a fundamental level", e.g. by modifying class loading. There's no other possible category but you can create a PR with a better description if you are concerned.
