### ISSUE TITLE
Add licenses

### ISSUE THREAD

**Issue by akullpp** [akullpp/awesome-java#697]
Would be nice to see the licenses which are used for the latest versions of the entries.

Especially for commercial use in enterprise settings this is very important.

This is quite complicated since there can be multiple applicable licenses.

**Comment by heldev** [comment]
How do you see it (let's consider simple cases only for one, with one license) ?
I mean do you want to use tags, some icons or something else?

**Comment by akullpp** [comment]
I think we need to be careful not to include too many meta information since it could create an user experience issue. Currently we only have the information if it's commercial.

Regarding licenses: Most of them are fine for projects in a business setting, except viral ones like GPL which are directly available to the end user or network licenses like AGPL which retain their virality.

**Comment by akullpp** [comment]
#742 

Should continuously check this.
