### ISSUE TITLE
Fully commercial and non-open-source entries

### ISSUE THREAD

**Issue by shathor** [akullpp/awesome-java#797]
It's subjective but I think there is a consensus that these are **not awesome** at all. Not even with the ![c]] marker. In my opinion they should be moved to a shame category or better entirely removed.
This only applies to fully commercial and non-open-source entries. **_Not_** those that have a commercial and non-commercial offering like JOOQ, IntelliJ or Flyway. Those are fine.

**Comment by tedyoung** [comment]
I'm curious where the consensus that non-open source entries aren't awesome? Can you point to a discussion on this?

**Comment by tvaughan77** [comment]
> I'm curious where the consensus that non-open source entries aren't awesome? Can you point to a discussion on this?

https://en.wikipedia.org/wiki/The_Cathedral_and_the_Bazaar

**Comment by akullpp** [comment]
> It's subjective but I think there is a consensus that these are **not awesome** at all. Not even with the ![c]] marker. In my opinion they should be moved to a shame category or better entirely removed.
> This only applies to fully commercial and non-open-source entries. **_Not_** those that have a commercial and non-commercial offering like JOOQ, IntelliJ or Flyway. Those are fine.

I understand and I tend to agree with you, but would like to have more opinions.

**Comment by akullpp** [comment]
Updated CONTRIBUTION.md:

> (iii) If commercial, it has clear pricing and at least one free tier.

Removed entries which do not comply.
