### ISSUE TITLE
Podcasts

### ISSUE THREAD

**Issue by Enahsh2o** [akullpp/awesome-java#81]
Under the podcast list, you have listed The Java Posse. Unfortunately, they have ended there show (I believe as of last month). I think it would be great to keep them on the list, but possibly note that the show has been ended so there won't be any new shows from them.
P.S. Sorry if this isn't technically an 'issue'. Still new to all of this. :)

**Comment by akullpp** [comment]
Thanks! I changed it: https://github.com/akullpp/awesome-java/pull/89
