### ISSUE TITLE
Cloudsmith Removed

### ISSUE THREAD

**Issue by lskillen** [akullpp/awesome-java#836]
Hey @akullpp - Sorry to bother you, but it looks like Cloudsmith was removed in https://github.com/akullpp/awesome-java/commit/9ed1924aa3f242b4e0efd75fb3866adbc1650685 due to free tier confusion. Cloudsmith absolutely does still have a free tier, and will continue to do so forever. We are also completely free for open-source as well, with an additional uplift in storage, bandwidth and features for those kinds of projects. Re-adding would be greatly appreciated!

Quote from [Cloudsmith](https://cloudsmith.io/package/plans/):

> Need a free account? Signup with any plan above; after your trial you'll be on our free tier, where you'll get 500MB of storage and 1GB of bandwidth (for public-only repositories).

**Comment by akullpp** [comment]
Great, I will add it.
