### ISSUE TITLE
Where to add Ghidra?

### ISSUE THREAD

**Issue by shathor** [akullpp/awesome-java#883]
Hi

I was wondering in which category you could add [Ghidra](https://www.ghidra-sre.org/), a software reverse engineering tool written in Java. Could it even be placed in this list?
Github link: https://github.com/NationalSecurityAgency/ghidra

Cheers.

**Comment by akullpp** [comment]
Better suited for awesome-security or a netsec list, we don't normally add programs just written in Java. Compare it with bytecode-viewer which is for Java specifically.
