### ISSUE TITLE
How can I add a link that spans through many resources related to Java/JVM?

### ISSUE THREAD

**Issue by neomatrix369** [akullpp/awesome-java#885]
I have been gathering a lot of Java-related resources related to AI/ML/DL here:
- https://github.com/neomatrix369/awesome-ai-ml-dl/blob/master/details/java-jvm.md#java

and about GraalVM, Wasm, and related tech here

- https://github.com/neomatrix369/awesome-graal

So these are not libraries or frameworks or packages but resources that are a collection of a whole lot of things

Would it be okay to add it under Documentation or Miscellaneous or Awesome lists or all of them? Please guide me, as I'll be creating a PR and would be happy to discuss this on it.

**Comment by akullpp** [comment]
See PRs.
