### ISSUE TITLE
Distributed workflow systems

### ISSUE THREAD

**Issue by heldev** [akullpp/awesome-java#910]
I keep bumping into tech (both OS and commercial) that is supposed to replace manually coded sagas and similar in distributed systems. Today it was https://github.com/temporalio/temporal / https://github.com/uber/cadence . I didn't have a chance to try them, but I see in real-life that people write their variations of them.  I use this list as a starting point of many investigations and if/when I need to make a choice I would appreciate having such a category. Ideally with a meaningful search-friendly description

Do we want to include them?
Or is there anyone who tried rolling them out at an organization and can tell if it's a good/bad idea?

**Comment by akullpp** [comment]
Orchestration platforms definitely have a use, so please create PR to include them :-)
