### ISSUE TITLE
Big Cleanup

### ISSUE THREAD

**Issue by akullpp** [akullpp/awesome-java#94]
No offense meant, just discussing ideas.

# Delete:

## Cloud Continuous Integration

Reason for removal:
1. Adaption rate really low
2. Extremely high fluctuation
3. Money grabbers

* CircleCI
* Codeship
* Travis (only one I'm considering not to delete)
## Distributed Applications

* JGroups, kind of unique application scope but outdated

## Machine Learning

* Apache Hadoop - while still in use, the map/reduce paradigm has strongly fallen from grace with leightweight approaches like Apache Spark provides, Mahout has switched also I think.
* Apache Mahout - the switch from map/reduce has to be evaluated.

## REST Frameworks

* Feign - Copy of Retrofit with less adaption rate. Although I currently see application of Feign in a Spring Boot project.

## Templating

* Velocity - Kind of defies what this list is about, last update was 2010 and there are alternatives.

# Merge

* **Database** (7) and **Distributed Databases** (2) or split into Databases and Database Tools

# Thoughts

Projects hosted on Google Code should be checked for an official GitHub repository. If there's none, it could be a strong indicator that it is dead. These are:

* [Thumbnailator](https://code.google.com/p/thumbnailator) - Thumbnailator is a high-quality thumbnail generation library for Java.
* [Lanterna](https://code.google.com/p/lanterna/) - Easy console text GUI library similar to curses.

**Comment by rasheedamir** [comment]
@akullpp why would you like to delete "Liquibase"? That is the most commonly used database migration tool. Maybe I have misunderstood the purpose of the list of stuff we are adding in "awesome-java"?

**Comment by akullpp** [comment]
Thanks for the comment which brings up one of the most fundamental issues which was discussed early on and needs to be updated in the contribution guidelines too.

Regarding "most commonly used": Take for example Apache Ant, I would argue that Ant is probably more widespread than Gradle and there are fields of application where Ant is in fact more suited than Gradle.

But you have a situation where a colleague is complaining about how bloaty Java is and you should do everything in JavaScript or Golang because they are awesome. What do you show them to convince them that Java is awesome? Your 10k lines Ant XML-configuration which evolved over 20 years and is the holy grail of configuration or the new shiny Gradle which admittedly gives you sometimes headaches?

The main point here is the adjective "awesome" which many "awesome lists" do not define or care about and just list every damn plugin because it's easy to do so. You neither have to think nor judge nor re-evaluate the decisions.

But I see your point and would like more input.

**Comment by akullpp** [comment]
Proposal: We add another Oldie Section

**Comment by mosabua** [comment]
As mentioned in PR 152 I suggest to add Hudson back in. It is used in some VERY large deployments including to build Java/JDK itself and is an active, well maintained top level Eclipse project.

**Comment by shaikhmshariq** [comment]
Thumbnailator code base is available now on Github https://github.com/coobird/thumbnailator

**Comment by akullpp** [comment]
@shaikhmshariq a PR would be welcome!

**Comment by shaikhmshariq** [comment]
Not able to do so.. 

![2015-08-12 16_31_09-calendar - shaikh shariq nividous com - outlook](https://cloud.githubusercontent.com/assets/1113616/9222484/b5e1dcd6-410f-11e5-8740-2ed620aed832.png)

![2015-08-12 16_31_32-calendar - shaikh shariq nividous com - outlook](https://cloud.githubusercontent.com/assets/1113616/9222485/b5e2bb42-410f-11e5-8bb1-a23e1785d301.png)

**Comment by akullpp** [comment]
Added the new URL in the latest refactoring.

**Comment by akullpp** [comment]
Added an "Ancients" section right at the beginning to appreciate the continuing work of robust libraries.

**Comment by geoand** [comment]
@akullpp I expect Feign's will start being used heavily (although implicitly) with the adoption of Spring Cloud

**Comment by pron** [comment]
JGroups may be mature, but it is certainly not outdated. It has certain algorithms (like Raft and other protocols) that are offered by no other library, and it serves as the very core of JBoss Infinispan. It is a strong ZooKeeper competitor (and much much more), even if sadly not many people know about it.

As to Hadoop, I don't know about it's applicability to machine learning (a subject I'm not involved with), but it would seem strange to omit such a central, widepsread Java project.

**Comment by pmwmedia** [comment]
Lanterna is on Github https://github.com/mabe02/lanterna and seems to be alive.

**Comment by akullpp** [comment]
Cloud CIs deleted for now, until someone comes with a good reason to include them.

GitHub URLs adapter.

Hadoop moved to Ancients section.
Freemarker and Velocity to Ancients.

JGroups stays, see comment.
Feign stays for now.

No idea yet how to handle the database and distributed databases sections.

**Comment by pron** [comment]
I think that the "Ancients" section is confusing:

1.  It is not really a well-defined category, so when will I ever look there? For example, I find it weird that JUnit (and TestNG), the most important Java testing library by far is not to be found in the testing section. Similarly for for JML and Trove, that are still the leading tools in their respective areas. It just hides the most popular tools in some categories (should Java itself be in this section merely by virtue of its age?).

2. It has a subjective judgment, *In existence since the beginning of time and which will continue being used long after the hype has waned*, which is very hard to interpret. What does that even mean? That those are the best tools, which stood the test of time? That they are the best known ones? That they are outdated but still have a large market share? Is it a hall of fame or a hall of shame? Each of these interpretation is true for some of the tools and not for others, so in addition to being hard to find, these tools have a label that is mostly confusing. 

If you think a tool is outdated, it's best to leave it in its own category and note that (e.g., cglib). Similarly if you think that the tool is an unmatched classic (e.g., JUnit).

**Comment by akullpp** [comment]
Good idea, you could do a PR. The original issue still exists however. The scope of awesome should probably not include outdated (e.g. Velocity) or highly disregarded frameworks (e.g. JSF)

**Comment by akullpp** [comment]
Disperse the `Ancients` category.

**Comment by akullpp** [comment]
Let's track this in separate issues.
